/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import vista.Principal;
import vista.interfaces.IConstanteComponentes;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class PanelPrincipal extends javax.swing.JPanel implements IConstanteComponentes{

    private final Principal principal;
    /**
     * Creates new form PanelPrincipal
     * @param principal
     */
    public PanelPrincipal(Principal principal) {
        initComponents();
        this.principal = principal;
        this.agregarEventoLabels();
        PanelComponents.modificarElementos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxRol = new javax.swing.JComboBox<>();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelInfoCorreo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelInfoTelefono = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelInfoDireccion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(144, 144, 144));

        jComboBoxRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxRol.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Usuario", "Estudiante", "Docente", "Directivo", "Personal de Servicio" }));
        jComboBoxRol.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        jComboBoxRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolActionPerformed(evt);
            }
        });

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setText("Usuario");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        jPasswordFieldClave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordFieldClave.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldClave.setText("clave");
        jPasswordFieldClave.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        jButtonEntrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setToolTipText("");
        jButtonEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(88, 165, 240));

        jLabelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Inicio de Sesion");

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/herramientas/close.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(0, 613, Short.MAX_VALUE)
                .addComponent(jLabelCerrar)
                .addContainerGap())
            .addComponent(jLabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCerrar)
                .addGap(31, 31, 31)
                .addComponent(jLabelHeader)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanelInfo.setBackground(new java.awt.Color(0, 107, 196));
        jPanelInfo.setPreferredSize(new java.awt.Dimension(95, 403));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/principal/school-login.png"))); // NOI18N
        jLabelImagen.setToolTipText("Clic aquí para más información");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("<html><body><p>Sistema de gestión de Colegios</p></body></html>");

        jPanelInfoCorreo.setBackground(new java.awt.Color(0, 107, 196));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/principal/email.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ejemplo@corejemplo.com");

        javax.swing.GroupLayout jPanelInfoCorreoLayout = new javax.swing.GroupLayout(jPanelInfoCorreo);
        jPanelInfoCorreo.setLayout(jPanelInfoCorreoLayout);
        jPanelInfoCorreoLayout.setHorizontalGroup(
            jPanelInfoCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCorreoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoCorreoLayout.setVerticalGroup(
            jPanelInfoCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelInfoTelefono.setBackground(new java.awt.Color(0, 107, 196));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/principal/mobile-phone.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("3125689782");

        javax.swing.GroupLayout jPanelInfoTelefonoLayout = new javax.swing.GroupLayout(jPanelInfoTelefono);
        jPanelInfoTelefono.setLayout(jPanelInfoTelefonoLayout);
        jPanelInfoTelefonoLayout.setHorizontalGroup(
            jPanelInfoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoTelefonoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoTelefonoLayout.setVerticalGroup(
            jPanelInfoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoTelefonoLayout.createSequentialGroup()
                .addGroup(jPanelInfoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelInfoDireccion.setBackground(new java.awt.Color(0, 107, 196));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/school-building.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Calle 5 Cr 4-17");

        javax.swing.GroupLayout jPanelInfoDireccionLayout = new javax.swing.GroupLayout(jPanelInfoDireccion);
        jPanelInfoDireccion.setLayout(jPanelInfoDireccionLayout);
        jPanelInfoDireccionLayout.setHorizontalGroup(
            jPanelInfoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoDireccionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoDireccionLayout.setVerticalGroup(
            jPanelInfoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoDireccionLayout.createSequentialGroup()
                .addGroup(jPanelInfoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jLabelTitulo)
            .addComponent(jPanelInfoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInfoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInfoDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelInfoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelInfoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(102, 102, 102));
        jLabelText.setText("Ingrese los datos para acceder al sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsuario)
                                    .addComponent(jPasswordFieldClave)
                                    .addComponent(jComboBoxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelText, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelText)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        jComboBoxRol.getAccessibleContext().setAccessibleParent(this);
        jTextFieldUsuario.getAccessibleContext().setAccessibleParent(this);
        jPasswordFieldClave.getAccessibleContext().setAccessibleParent(this);
        jButtonEntrar.getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        entrar();
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jComboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        cerrarApp();
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoCorreo;
    private javax.swing.JPanel jPanelInfoDireccion;
    private javax.swing.JPanel jPanelInfoTelefono;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    private void entrar() {
        String usuario = this.jTextFieldUsuario.getText();
        String clave = new String(this.jPasswordFieldClave.getPassword());
        switch(this.jComboBoxRol.getSelectedIndex()){
            case 0:
                return;
            case 1:
                this.irAEstudiante(usuario, clave);
                break;
            case 2:
                break;
            case 3:
                this.irADirectivos(usuario, clave);
        }
    }

    private void agregarEventoLabels() {
        this.jTextFieldUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                PanelComponents.addPlaceHolder(jTextFieldUsuario, TEXTFIELD_USUARIO, "");
            }
            

            @Override
            public void focusLost(FocusEvent e) {
                PanelComponents.addPlaceHolder(jTextFieldUsuario, "", TEXTFIELD_USUARIO);
            }
        });
        
        this.jPasswordFieldClave.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                PanelComponents.addPlaceHolder(jPasswordFieldClave, PASSWORDFIELD_CLAVE, "");
            }

            @Override
            public void focusLost(FocusEvent e) {
                PanelComponents.addPlaceHolder(jPasswordFieldClave, "", PASSWORDFIELD_CLAVE);
            }
        });
    }

    private void cerrarApp() {
        this.principal.preguntarAlCerrar();
    }

    private void irADirectivos(String usuario, String clave) {
        if(buscarDirectivo(usuario, clave)){
            this.principal.irADirectivos(usuario);
        }
    }

    private boolean buscarDirectivo(String usuario, String clave) {

        return true;
    }

    private void irAEstudiante(String usuario, String clave) {
        if(buscarEstudiante(usuario,clave)){
            this.principal.irAEstudiante(usuario);
        }
    }

    private boolean buscarEstudiante(String usuario, String clave) {
        return true;
    }
}
