/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.estudiante;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import vista.Principal;
import vista.interfaces.IConstanteComponentes;
import vista.paneles.PanelDashboard;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class PanelEstudiante extends PanelDashboard implements IConstanteComponentes {

    private final Principal principal;
    private final String usuario;
    /**
     * Creates new form PanelEstudiante
     * @param principal
     * @param usuario
     */
    public PanelEstudiante(Principal principal, String usuario) {
        initComponents();
        this.principal = principal;
        this.usuario = usuario;
        this.modificarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelActividades = new javax.swing.JPanel();
        jLabelImagenActividades = new javax.swing.JLabel();
        jLabelTotalActividades = new javax.swing.JLabel();
        jPanelDeudas = new javax.swing.JPanel();
        jLabelImagenDeudores = new javax.swing.JLabel();
        jLabelDeudaTotal = new javax.swing.JLabel();
        jLabelTituloTPersona = new javax.swing.JLabel();
        jLabelTituloTPersona1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTareas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelActividades.setBackground(new java.awt.Color(230, 230, 230));

        jLabelImagenActividades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/directivos/school-calendar-120px.png"))); // NOI18N

        jLabelTotalActividades.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelTotalActividades.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTotalActividades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalActividades.setText("<html><body>Tareas Pendientes:<br><center></center></body></html>");
        jLabelTotalActividades.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelActividadesLayout = new javax.swing.GroupLayout(jPanelActividades);
        jPanelActividades.setLayout(jPanelActividadesLayout);
        jPanelActividadesLayout.setHorizontalGroup(
            jPanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTotalActividades, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanelActividadesLayout.setVerticalGroup(
            jPanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActividadesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelImagenActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelDeudas.setBackground(new java.awt.Color(230, 230, 230));

        jLabelImagenDeudores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenDeudores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/directivos/calculadora-120px.png"))); // NOI18N

        jLabelDeudaTotal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelDeudaTotal.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDeudaTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDeudaTotal.setText("<html><body>Deudas Pendientes:<br><center></center></body></html>");
        jLabelDeudaTotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelDeudasLayout = new javax.swing.GroupLayout(jPanelDeudas);
        jPanelDeudas.setLayout(jPanelDeudasLayout);
        jPanelDeudasLayout.setHorizontalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenDeudores, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(jLabelDeudaTotal)
        );
        jPanelDeudasLayout.setVerticalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeudasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelImagenDeudores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDeudaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelTituloTPersona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloTPersona.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTPersona.setText("Trabajos Pendientes");

        jLabelTituloTPersona1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloTPersona1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloTPersona1.setText("Actividades Extra Escolares");

        jScrollPane1.setBorder(null);

        jTableTareas.setAutoCreateRowSorter(true);
        jTableTareas.setForeground(new java.awt.Color(110, 110, 110));
        jTableTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTareas.setGridColor(new java.awt.Color(204, 204, 204));
        jTableTareas.setSelectionBackground(new java.awt.Color(88, 165, 240));
        jScrollPane1.setViewportView(jTableTareas);

        jScrollPane2.setBorder(null);

        jTableActividades.setAutoCreateRowSorter(true);
        jTableActividades.setForeground(new java.awt.Color(110, 110, 110));
        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableActividades.setGridColor(new java.awt.Color(204, 204, 204));
        jTableActividades.setSelectionBackground(new java.awt.Color(88, 165, 240));
        jScrollPane2.setViewportView(jTableActividades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jPanelDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloTPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloTPersona1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloTPersona)
                    .addComponent(jLabelTituloTPersona1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDeudaTotal;
    private javax.swing.JLabel jLabelImagenActividades;
    private javax.swing.JLabel jLabelImagenDeudores;
    private javax.swing.JLabel jLabelTituloTPersona;
    private javax.swing.JLabel jLabelTituloTPersona1;
    private javax.swing.JLabel jLabelTotalActividades;
    private javax.swing.JPanel jPanelActividades;
    private javax.swing.JPanel jPanelDeudas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableActividades;
    private javax.swing.JTable jTableTareas;
    // End of variables declaration//GEN-END:variables
    
    private void modificarTabla() {
        modificarGridTabla(jTableActividades);
        modificarAlturaFilas(jTableActividades);
        renderizarTabla(jTableActividades);
        
        modificarGridTabla(jTableTareas);
        modificarAlturaFilas(jTableTareas);
        renderizarTabla(jTableTareas);
    }

    @Override
    protected void construirTexto(Object data, JLabel target, String mensaje) {
        String inicioTexto = "<html><body>";
        String finalTexto = "</body></html>";
        
        String cad = inicioTexto + mensaje + ": " + "<br><center>" + data + "</center>" + finalTexto;
        
        target.setText(cad);
    }

    @Override
    protected void cargarDatos() {
        imprimirNumeroDeudas();
        imprimirNumeroTrabajos();
        
        cargarActividadesEstudiante();
    }

    private void imprimirNumeroDeudas() {
        int numeroDeudas = this.principal.obtenerCantidadDeudasEst(usuario);
        construirTexto(numeroDeudas, jLabelDeudaTotal, "Deudas Pendientes");
    }

    private void imprimirNumeroTrabajos() {
        int numeroTrabajos = this.principal.obtenerCantidadTrabajosEst(usuario);
        construirTexto(numeroTrabajos, jLabelTotalActividades, "Trabajos Pendientes");
    }

    private void cargarActividadesEstudiante() {
        String[] columnas = {
            "Actividad",
            "Descripcion",
            "Docente",
            "Materia",
            "Periodo",
        };
        String[][] personas = this.principal.obtenerTareasEstudiante(columnas.length, usuario);
        TableModel modelo = new DefaultTableModel(personas, columnas);
        this.jTableTareas.setModel(modelo);
    }
}
