/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.directivo;

import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import vista.Principal;
import vista.interfaces.IConstanteComponentes;
import vista.paneles.PanelComponents;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class PanelDeudas extends PanelComponents implements IConstanteComponentes{
    
    private final Principal principal;
    private JMenuItem jMenuItemAgregarEstudiantes;
    private JMenuItem jMenuItemEliminar;
    private Timer timerBuscar;
    /**
     * Creates new form PanelRutas
     * @param principal
     */
    public PanelDeudas(Principal principal) {
        this.principal = principal;
        initComponents();
        cargarDatos();
        eventuarComponentes();
        agregarPlaceHolder();
        modificarTabla(jTableDeudas);
        try {
            agregarFocusBorder(jPanelRegistro, jPanelDeudas, jPanelBuscar);
            modificarTemaComboBox(jPanelRegistro);
            cambiarEstiloTabbePane(jTabbedPaneRutas);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(PanelDeudas.class.getName()).log(Level.SEVERE, null, ex);
        }
        iniciarTimerBuscar(jTableDeudas, jTextFieldBuscar, timerBuscar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuDeudas = new javax.swing.JPopupMenu();
        jTabbedPaneRutas = new javax.swing.JTabbedPane();
        jPanelDeudas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeudas = new javax.swing.JTable();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanelRegistro = new javax.swing.JPanel();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jComboBoxEstudiante = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDescripcion = new javax.swing.JTextPane();

        jPopupMenuDeudas.setInvoker(jTableDeudas);

        setBackground(new java.awt.Color(88, 165, 240));

        jTabbedPaneRutas.setBackground(new java.awt.Color(88, 165, 240));
        jTabbedPaneRutas.setForeground(new java.awt.Color(255, 255, 255));

        jPanelDeudas.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        jTableDeudas.setAutoCreateRowSorter(true);
        jTableDeudas.setForeground(new java.awt.Color(110, 110, 110));
        jTableDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDeudas.setGridColor(new java.awt.Color(204, 204, 204));
        jTableDeudas.setSelectionBackground(new java.awt.Color(88, 165, 240));
        jTableDeudas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableDeudas);

        jPanelBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/busqueda/search.png"))); // NOI18N

        jTextFieldBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldBuscar.setText("Buscar");
        jTextFieldBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldBuscar)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDeudasLayout = new javax.swing.GroupLayout(jPanelDeudas);
        jPanelDeudas.setLayout(jPanelDeudasLayout);
        jPanelDeudasLayout.setHorizontalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeudasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeudasLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanelDeudasLayout.setVerticalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeudasLayout.createSequentialGroup()
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneRutas.addTab("Ver", jPanelDeudas);

        jPanelRegistro.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldValor.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldValor.setText("Valor");
        jTextFieldValor.setToolTipText("");
        jTextFieldValor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setToolTipText("");
        jButtonRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setToolTipText("");
        jButtonLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jComboBoxEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxEstudiante.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante" }));
        jComboBoxEstudiante.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        jScrollPane2.setBorder(null);

        jTextPaneDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextPaneDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPaneDescripcion.setForeground(new java.awt.Color(102, 102, 102));
        jTextPaneDescripcion.setText("Descripcion");
        jScrollPane2.setViewportView(jTextPaneDescripcion);

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, 0, 447, Short.MAX_VALUE))))
                    .addGroup(jPanelRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 308, Short.MAX_VALUE))
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPaneRutas.addTab("Registro", jPanelRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRutas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRutas)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxEstudiante;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelDeudas;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPopupMenu jPopupMenuDeudas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneRutas;
    private javax.swing.JTable jTableDeudas;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextPane jTextPaneDescripcion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registrar() {
        if (validar()) {
            JOptionPane.showMessageDialog(null, "Se ha registrado la ruta correctamente", "Rutas", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No Se ha registrado la ruta", "Rutas", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean buscar() {
        String placa = this.jTextFieldValor.getText();
        return this.principal.buscarRuta(placa);
    }

    @Override
    public boolean validar() {
        try{
            if(this.jComboBoxEstudiante.getSelectedIndex() == 0){
                return false;
            } else if(this.jTextPaneDescripcion.getText().equals("")){
                return false;
            } else if(this.jTextFieldValor.getText().equals("")){
                return false;
            }
            
            int codigo = Integer.parseInt(((String)this.jComboBoxEstudiante.getSelectedItem()).split("-")[0]);
            double valor = Double.parseDouble(this.jTextFieldValor.getText());
            String descripcion = this.jTextPaneDescripcion.getText();
            return this.principal.crearDeudaAEstudiante(codigo, valor, descripcion);
            
        }catch(NullPointerException | IndexOutOfBoundsException | NumberFormatException ex){
            System.out.println(ex.getMessage());
            return false;
        }
    }

    private void cargarDatos() {
        cargarDatosPrincipales();
        cargarEstudiantes();
    }
    
    private void cargarEstudiantes(){
        String[] estudiantes = this.principal.obtenerEstudiantesPorCodigo();
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Estudiantes");
        for(int i = 0 ; i < estudiantes.length; i++){
            modelo.addElement(estudiantes[i]);
        }
        
        this.jComboBoxEstudiante.setModel(modelo);
        
    }

    private void eventuarComponentes() {
        iniciarItemsPopMenu(jTableDeudas, jPopupMenuDeudas);
        eventuarTabs(jTabbedPaneRutas);
    }

    @Override
    public void agregarItemsAMenu() {
        this.jMenuItemAgregarEstudiantes = new JMenuItem("Agregar Estudiantes");
        this.jMenuItemEliminar = new JMenuItem("Eliminar Ruta");
        
        this.jMenuItemAgregarEstudiantes.addActionListener((ActionEvent e) -> {
            agregarEstudiantesARuta();
        });
        
        this.jPopupMenuDeudas.add(jMenuItemAgregarEstudiantes);
        this.jPopupMenuDeudas.add(jMenuItemEliminar);
    }

    private void agregarEstudiantesARuta() {
        String placa = obtenerInformaciónCelda(jTableDeudas, 0).toString();
        this.principal.irAPanelRutasEstudiante(placa);
    }

    @Override
    public void agregarPlaceHolder() {
        this.jTextFieldBuscar.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                addPlaceHolder(jTextFieldBuscar, TEXTFIELD_BUSCAR, "");
            }

            @Override
            public void focusLost(FocusEvent e) {
                addPlaceHolder(jTextFieldBuscar, "", TEXTFIELD_BUSCAR);
            }
        });
        
        this.jTextFieldValor.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                addPlaceHolder(jTextFieldValor, TEXTFIELD_VALOR, "");
            }

            @Override
            public void focusLost(FocusEvent e) {
                addPlaceHolder(jTextFieldValor, "", TEXTFIELD_VALOR);
            }
        });
        
        this.jTextPaneDescripcion.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                addPlaceHolder(jTextPaneDescripcion, TEXTPANE_DESCRIPCION_DEUDAS, "");
            }

            @Override
            public void focusLost(FocusEvent e) {
                addPlaceHolder(jTextPaneDescripcion, "", TEXTPANE_DESCRIPCION_DEUDAS);
            }
        });
    }

    @Override
    public Object cargarDatosPrincipales() {
        String[] columnas = {
            "ID",
            "Valor",
            "Descripción",
            "Estudiante",};
        String[][] datos = this.principal.obtenerTodasLasDeudas(columnas.length);

        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        this.jTableDeudas.setModel(modelo);
        return modelo;
    }

    @Override
    public void agregarTextosDefecto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
