/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.directivo;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import vista.Principal;
import vista.paneles.PanelComponents;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class PanelAcudienteEstudiante extends PanelComponents {

    private final Principal principal;
    /**
     * Creates new form PanelAcudiente
     * @param principal
     */
    public PanelAcudienteEstudiante(Principal principal) {
        this.principal = principal;
        initComponents();
        cargarDatosPrincipales();
        cargarAcudientesTemp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jListAcudientes = new javax.swing.JList<>();
        jButtonAgregarAcudiente = new javax.swing.JButton();
        jButtonQuitarAcudiente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAcudientesAgregar = new javax.swing.JList<>();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(null);

        jListAcudientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jListAcudientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jListAcudientes.setForeground(new java.awt.Color(110, 110, 110));
        jListAcudientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No hay Acudientes Registrados" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAcudientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAcudientes.setSelectionBackground(new java.awt.Color(88, 165, 240));
        jScrollPane3.setViewportView(jListAcudientes);

        jButtonAgregarAcudiente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregarAcudiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAgregarAcudiente.setForeground(new java.awt.Color(88, 165, 240));
        jButtonAgregarAcudiente.setText("Agregar");
        jButtonAgregarAcudiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240)));
        jButtonAgregarAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAcudienteActionPerformed(evt);
            }
        });

        jButtonQuitarAcudiente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQuitarAcudiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonQuitarAcudiente.setForeground(new java.awt.Color(88, 165, 240));
        jButtonQuitarAcudiente.setText("Quitar");
        jButtonQuitarAcudiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240)));
        jButtonQuitarAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarAcudienteActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(null);

        jListAcudientesAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jListAcudientesAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jListAcudientesAgregar.setForeground(new java.awt.Color(110, 110, 110));
        jListAcudientesAgregar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No has cargado ningun acudiente" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAcudientesAgregar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAcudientesAgregar.setSelectionBackground(new java.awt.Color(88, 165, 240));
        jScrollPane4.setViewportView(jListAcudientesAgregar);

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setToolTipText("");
        jButtonRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setToolTipText("");
        jButtonLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(88, 165, 240));
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setToolTipText("");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 165, 240), 2));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(88, 165, 240));

        jLabelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Agregar Acudientes a Estudiantes");

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menu/close.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCerrar)
                .addContainerGap())
            .addComponent(jLabelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHeader)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonQuitarAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonAgregarAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonQuitarAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAcudienteActionPerformed
        agregarAcudiente();
    }//GEN-LAST:event_jButtonAgregarAcudienteActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        ocultarPanel();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonQuitarAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarAcudienteActionPerformed
        quitarAcudiente();
    }//GEN-LAST:event_jButtonQuitarAcudienteActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        ocultarPanel();
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarAcudiente;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonQuitarAcudiente;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JList<String> jListAcudientes;
    private javax.swing.JList<String> jListAcudientesAgregar;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private void agregarAcudiente() {
        String[] acudienteData = this.jListAcudientes.getSelectedValue().split("-");
        long documento = Long.parseLong(acudienteData[0]);
        
        this.principal.agregarAcudientesTemp(documento);
        cargarNuevosAcudientesALista();
    }

    @Override
    public void registrar() {
        if(validar()){
            JOptionPane.showMessageDialog(null,"Se ha cargado correctamente los acudientes","Agregar acudientes a estudiante",JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null,"No se ha cargado correctamente los acudientes","Agregar acudientes a estudiante",JOptionPane.ERROR_MESSAGE);        
        }
    }

    @Override
    public boolean validar() {
        try{
            if(this.jListAcudientesAgregar.getModel().getElementAt(0).equals("No has cargado ningun acudiente")){
                return false;
            }else if(this.jListAcudientesAgregar.getModel().getSize() == 0){
                return false;
            }
            this.principal.ocultarDialog();
            return true;
        }catch(NullPointerException | IndexOutOfBoundsException | NumberFormatException ex){
            System.err.println(ex.getMessage());
            return false;
        }
    }

    private void cargarNuevosAcudientesALista() {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        String[] nuevosAc = this.principal.obtenerAcudientesTemp();
        for(int i = 0 ; i < nuevosAc.length; i++){
            modelo.addElement(nuevosAc[i]);
        }
        this.jListAcudientesAgregar.setModel(modelo);
        
    }

    private void quitarAcudiente() {
        String[] acData = this.jListAcudientesAgregar.getSelectedValue().split("-");
        if(this.principal.quitarAcudienteTemp(Long.parseLong(acData[0]))){
            cargarNuevosAcudientesALista();
        }
    }

    private void ocultarPanel() {
        this.principal.ocultarDialog();
    }

    private void cargarAcudientesTemp() {
        int acTemp = this.principal.obtenerCantAcudientesTemp();
        
        if(acTemp > 0){
            cargarNuevosAcudientesALista();
        }
    }

    @Override
    public Object cargarDatosPrincipales() {
        String[] acudientes = this.principal.obtenerAcudientesPorDocumento();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        if(acudientes.length == 0){
            modelo.addElement("No hay Acudientes Registrados");
        }
        
        for(int i = 0 ; i < acudientes.length; i++){
            modelo.addElement(acudientes[i]);
        }

        this.jListAcudientes.setModel(modelo);
        return modelo;
    }

    @Override
    public boolean buscar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void agregarItemsAMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void agregarPlaceHolder() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void agregarTextosDefecto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
