/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles.menu;

import java.awt.Color;
import javax.swing.JPanel;
import vista.Principal;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class MenuDirectivo extends javax.swing.JPanel {

    private final Principal principal;
    private final String usuario;
    private final Color colorMouseEntered = new Color(17, 147, 255);
    private final Color colorMouseExited = new Color(0,107,196);
    private final Color colorMouseClicked = new Color(50, 162, 255);
    private boolean cambiarColorEps = true;
    private boolean cambiarColorDepartamento = true;
    private boolean cambiarColorAreas = true;
    private boolean cambiarColorPersonas = true;
    private boolean cambiarColorCursos = true;
    private boolean cambiarColorRutas = true;
    private boolean cambiarColorDeudas = true;
    private boolean cambiarColorDashboard = true;

    /**
     * Creates new form MenuDirectivo
     * @param principal
     * @param usuario
     */
    public MenuDirectivo(Principal principal, String usuario) {

        initComponents();
        this.principal = principal;
        this.usuario = usuario;
        /*try {
            this.cargarEstiloBotones();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.put("TextField.border", BorderFactory.createCompoundBorder(new CustomeBorder(), new EmptyBorder(new Insets(4,4,4,4))));
            SwingUtilities.updateComponentTreeUI(this);
            this.jButtonAgregarPersonas.setUI(this.buttonui[0]);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        //menu.setLayout(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEps = new javax.swing.JPanel();
        jLabelImagenEps = new javax.swing.JLabel();
        jLabelTextEps = new javax.swing.JLabel();
        jPanelDepartamentos = new javax.swing.JPanel();
        jLabelImagenDepartamento = new javax.swing.JLabel();
        jLabelTextDepartamentos = new javax.swing.JLabel();
        jPanelAreas = new javax.swing.JPanel();
        jLabelImagenArea = new javax.swing.JLabel();
        jLabelTextAreas = new javax.swing.JLabel();
        jPanelPersonas = new javax.swing.JPanel();
        jLabelImagenPersonas = new javax.swing.JLabel();
        jLabelTextPersonas = new javax.swing.JLabel();
        jPanelCursos = new javax.swing.JPanel();
        jLabelImagenCursos = new javax.swing.JLabel();
        jLabelTextCursos = new javax.swing.JLabel();
        jPanelRutas = new javax.swing.JPanel();
        jLabelImagenRutas = new javax.swing.JLabel();
        jLabelTextRutas = new javax.swing.JLabel();
        jPanelDeudas = new javax.swing.JPanel();
        jLabelImagenDeudas = new javax.swing.JLabel();
        jLabelTextDeudas = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jPanelDashboard = new javax.swing.JPanel();
        jLabelImagenDashboard = new javax.swing.JLabel();
        jLabelTextDashboard = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 107, 196));

        jPanelEps.setBackground(new java.awt.Color(0, 107, 196));
        jPanelEps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEps.setPreferredSize(new java.awt.Dimension(315, 50));
        jPanelEps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEpsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEpsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelEpsMousePressed(evt);
            }
        });

        jLabelImagenEps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/hospital-2.png"))); // NOI18N

        jLabelTextEps.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextEps.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextEps.setText("EPS Y Salud Estudiantil");

        javax.swing.GroupLayout jPanelEpsLayout = new javax.swing.GroupLayout(jPanelEps);
        jPanelEps.setLayout(jPanelEpsLayout);
        jPanelEpsLayout.setHorizontalGroup(
            jPanelEpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEpsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenEps)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextEps, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEpsLayout.setVerticalGroup(
            jPanelEpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenEps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextEps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelDepartamentos.setBackground(new java.awt.Color(0, 107, 196));
        jPanelDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDepartamentos.setPreferredSize(new java.awt.Dimension(199, 50));
        jPanelDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDepartamentosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDepartamentosMousePressed(evt);
            }
        });

        jLabelImagenDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/school-building.png"))); // NOI18N

        jLabelTextDepartamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextDepartamentos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextDepartamentos.setText("Departamentos");

        javax.swing.GroupLayout jPanelDepartamentosLayout = new javax.swing.GroupLayout(jPanelDepartamentos);
        jPanelDepartamentos.setLayout(jPanelDepartamentosLayout);
        jPanelDepartamentosLayout.setHorizontalGroup(
            jPanelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepartamentosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImagenDepartamento)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDepartamentosLayout.setVerticalGroup(
            jPanelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabelTextDepartamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAreas.setBackground(new java.awt.Color(0, 107, 196));
        jPanelAreas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelAreas.setPreferredSize(new java.awt.Dimension(208, 50));
        jPanelAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAreasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAreasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelAreasMousePressed(evt);
            }
        });

        jLabelImagenArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/music-class.png"))); // NOI18N

        jLabelTextAreas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextAreas.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextAreas.setText("Areas y Materias");

        javax.swing.GroupLayout jPanelAreasLayout = new javax.swing.GroupLayout(jPanelAreas);
        jPanelAreas.setLayout(jPanelAreasLayout);
        jPanelAreasLayout.setHorizontalGroup(
            jPanelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAreasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenArea)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAreasLayout.setVerticalGroup(
            jPanelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextAreas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelPersonas.setBackground(new java.awt.Color(0, 107, 196));
        jPanelPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPersonas.setPreferredSize(new java.awt.Dimension(156, 50));
        jPanelPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPersonasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPersonasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelPersonasMousePressed(evt);
            }
        });

        jLabelImagenPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/avatar.png"))); // NOI18N

        jLabelTextPersonas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextPersonas.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextPersonas.setText("Personas");

        javax.swing.GroupLayout jPanelPersonasLayout = new javax.swing.GroupLayout(jPanelPersonas);
        jPanelPersonas.setLayout(jPanelPersonasLayout);
        jPanelPersonasLayout.setHorizontalGroup(
            jPanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenPersonas)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPersonasLayout.setVerticalGroup(
            jPanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenPersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextPersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelCursos.setBackground(new java.awt.Color(0, 107, 196));
        jPanelCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCursos.setPreferredSize(new java.awt.Dimension(140, 50));
        jPanelCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCursosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCursosMousePressed(evt);
            }
        });

        jLabelImagenCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/online-course.png"))); // NOI18N

        jLabelTextCursos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextCursos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextCursos.setText("Cursos");

        javax.swing.GroupLayout jPanelCursosLayout = new javax.swing.GroupLayout(jPanelCursos);
        jPanelCursos.setLayout(jPanelCursosLayout);
        jPanelCursosLayout.setHorizontalGroup(
            jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenCursos)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCursosLayout.setVerticalGroup(
            jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelRutas.setBackground(new java.awt.Color(0, 107, 196));
        jPanelRutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRutas.setPreferredSize(new java.awt.Dimension(140, 50));
        jPanelRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRutasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRutasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRutasMousePressed(evt);
            }
        });

        jLabelImagenRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/school-bus.png"))); // NOI18N

        jLabelTextRutas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextRutas.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextRutas.setText("Rutas");

        javax.swing.GroupLayout jPanelRutasLayout = new javax.swing.GroupLayout(jPanelRutas);
        jPanelRutas.setLayout(jPanelRutasLayout);
        jPanelRutasLayout.setHorizontalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRutasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenRutas)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRutasLayout.setVerticalGroup(
            jPanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelDeudas.setBackground(new java.awt.Color(0, 107, 196));
        jPanelDeudas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDeudas.setPreferredSize(new java.awt.Dimension(140, 50));
        jPanelDeudas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDeudasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDeudasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDeudasMousePressed(evt);
            }
        });

        jLabelImagenDeudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/calculadora.png"))); // NOI18N

        jLabelTextDeudas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextDeudas.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextDeudas.setText("Deudas");

        javax.swing.GroupLayout jPanelDeudasLayout = new javax.swing.GroupLayout(jPanelDeudas);
        jPanelDeudas.setLayout(jPanelDeudasLayout);
        jPanelDeudasLayout.setHorizontalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeudasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenDeudas)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDeudasLayout.setVerticalGroup(
            jPanelDeudasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenDeudas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextDeudas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelHeader.setBackground(new java.awt.Color(0, 107, 196));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Bienvenido Directivo");

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Usuario");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(0, 0, 0)
                .addComponent(jLabelUsuario)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jPanelDashboard.setBackground(new java.awt.Color(0, 107, 196));
        jPanelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDashboardMousePressed(evt);
            }
        });

        jLabelImagenDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/menuDirectivo/house.png"))); // NOI18N

        jLabelTextDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTextDashboard.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTextDashboard.setText("Dashboard");

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelImagenDashboard)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEps, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelRutas, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelEpsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEpsMouseEntered

        if (cambiarColorEps) {
            cambiarColorPanel(this.jPanelEps, colorMouseEntered);
            cambiarColorEps = true;
        }

    }//GEN-LAST:event_jPanelEpsMouseEntered

    private void jPanelEpsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEpsMouseExited

        if (cambiarColorEps) {
            cambiarColorPanel(this.jPanelEps, colorMouseExited);
            cambiarColorEps = true;
        }

    }//GEN-LAST:event_jPanelEpsMouseExited

    private void jPanelDepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDepartamentosMouseEntered
        if (cambiarColorDepartamento) {
            cambiarColorPanel(this.jPanelDepartamentos, colorMouseEntered);
            cambiarColorDepartamento = true;
        }
    }//GEN-LAST:event_jPanelDepartamentosMouseEntered

    private void jPanelDepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDepartamentosMouseExited
        if (cambiarColorDepartamento) {
            cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
            cambiarColorDepartamento = true;
        }
    }//GEN-LAST:event_jPanelDepartamentosMouseExited

    private void jPanelAreasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreasMouseEntered
        if (cambiarColorAreas) {
            cambiarColorPanel(jPanelAreas, colorMouseEntered);
            cambiarColorAreas = true;
        }
    }//GEN-LAST:event_jPanelAreasMouseEntered

    private void jPanelAreasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreasMouseExited
        if (cambiarColorAreas) {
            cambiarColorPanel(jPanelAreas, colorMouseExited);
            cambiarColorAreas = true;
        }
    }//GEN-LAST:event_jPanelAreasMouseExited

    private void jPanelPersonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPersonasMouseEntered
        if (cambiarColorPersonas) {
            cambiarColorPanel(jPanelPersonas, colorMouseEntered);
            cambiarColorPersonas = true;
        }
    }//GEN-LAST:event_jPanelPersonasMouseEntered

    private void jPanelPersonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPersonasMouseExited
        if (cambiarColorPersonas) {
            cambiarColorPanel(jPanelPersonas, colorMouseExited);
            cambiarColorPersonas = true;
        }
    }//GEN-LAST:event_jPanelPersonasMouseExited

    private void jPanelCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCursosMouseExited
        if (cambiarColorCursos) {
            cambiarColorPanel(jPanelCursos, colorMouseExited);
            cambiarColorCursos = true;
        }
    }//GEN-LAST:event_jPanelCursosMouseExited

    private void jPanelCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCursosMouseEntered
        if (cambiarColorCursos) {
            cambiarColorPanel(jPanelCursos, colorMouseEntered);
            cambiarColorCursos = true;
        }
    }//GEN-LAST:event_jPanelCursosMouseEntered

    private void jPanelRutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRutasMouseEntered
        if (cambiarColorRutas) {
            cambiarColorPanel(jPanelRutas, colorMouseEntered);
            cambiarColorRutas = true;
        }
    }//GEN-LAST:event_jPanelRutasMouseEntered

    private void jPanelRutasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRutasMouseExited
        if (cambiarColorRutas) {
            cambiarColorPanel(jPanelRutas, colorMouseExited);
            cambiarColorRutas = true;
        }
    }//GEN-LAST:event_jPanelRutasMouseExited

    private void jPanelDeudasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeudasMouseEntered
        if (cambiarColorDeudas) {
            cambiarColorPanel(jPanelDeudas, colorMouseEntered);
            cambiarColorDeudas = true;
        }
    }//GEN-LAST:event_jPanelDeudasMouseEntered

    private void jPanelDeudasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeudasMouseExited
        if (cambiarColorDeudas) {
            cambiarColorPanel(jPanelDeudas, colorMouseExited);
            cambiarColorDeudas = true;
        }
    }//GEN-LAST:event_jPanelDeudasMouseExited

    private void jPanelEpsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEpsMousePressed
        irAEps();
    }//GEN-LAST:event_jPanelEpsMousePressed

    private void jPanelDepartamentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDepartamentosMousePressed
        irARegistroDepartamentos();
    }//GEN-LAST:event_jPanelDepartamentosMousePressed

    private void jPanelAreasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreasMousePressed
        irAMaterias();
    }//GEN-LAST:event_jPanelAreasMousePressed

    private void jPanelPersonasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPersonasMousePressed
        irARegistroPersonas();
    }//GEN-LAST:event_jPanelPersonasMousePressed

    private void jPanelCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCursosMousePressed
        irACursos();
    }//GEN-LAST:event_jPanelCursosMousePressed

    private void jPanelRutasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRutasMousePressed
        irARutas();
    }//GEN-LAST:event_jPanelRutasMousePressed

    private void jPanelDeudasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeudasMousePressed
        irADeudas();
    }//GEN-LAST:event_jPanelDeudasMousePressed

    private void jPanelDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMouseEntered
        
        if (cambiarColorDashboard) {
            cambiarColorPanel(this.jPanelDashboard, colorMouseEntered);
            cambiarColorDashboard = true;
        }
    }//GEN-LAST:event_jPanelDashboardMouseEntered

    private void jPanelDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMouseExited
        
        if (cambiarColorDashboard) {
            cambiarColorPanel(this.jPanelDashboard, colorMouseExited);
            cambiarColorDashboard = true;
        }
    }//GEN-LAST:event_jPanelDashboardMouseExited

    private void jPanelDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashboardMousePressed
        irADirectivoInicio();
    }//GEN-LAST:event_jPanelDashboardMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagenArea;
    private javax.swing.JLabel jLabelImagenCursos;
    private javax.swing.JLabel jLabelImagenDashboard;
    private javax.swing.JLabel jLabelImagenDepartamento;
    private javax.swing.JLabel jLabelImagenDeudas;
    private javax.swing.JLabel jLabelImagenEps;
    private javax.swing.JLabel jLabelImagenPersonas;
    private javax.swing.JLabel jLabelImagenRutas;
    private javax.swing.JLabel jLabelTextAreas;
    private javax.swing.JLabel jLabelTextCursos;
    private javax.swing.JLabel jLabelTextDashboard;
    private javax.swing.JLabel jLabelTextDepartamentos;
    private javax.swing.JLabel jLabelTextDeudas;
    private javax.swing.JLabel jLabelTextEps;
    private javax.swing.JLabel jLabelTextPersonas;
    private javax.swing.JLabel jLabelTextRutas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelAreas;
    private javax.swing.JPanel jPanelCursos;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelDepartamentos;
    private javax.swing.JPanel jPanelDeudas;
    private javax.swing.JPanel jPanelEps;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelPersonas;
    private javax.swing.JPanel jPanelRutas;
    // End of variables declaration//GEN-END:variables

    private void irARegistroPersonas() {
        cambiarColorPanel(jPanelPersonas, colorMouseClicked);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorPersonas = false;
        cambiarColorDepartamento = true;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorDeudas = true;
        cambiarColorEps = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;

        this.principal.irAPersonas();
    }

    private void irARegistroDepartamentos() {
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseClicked);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorDepartamento = false;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorDeudas = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;

        this.principal.irADepartamentos();
    }

    private void irACursos() {

        cambiarColorPanel(jPanelCursos, colorMouseClicked);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorCursos = false;
        cambiarColorDepartamento = true;
        cambiarColorAreas = true;
        cambiarColorDeudas = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;

        this.principal.irACursos();
    }

    private void irAMaterias() {
        cambiarColorPanel(jPanelAreas, colorMouseClicked);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorAreas = false;
        cambiarColorDepartamento = true;
        cambiarColorCursos = true;
        cambiarColorDeudas = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;

        this.principal.irAMaterias();
    }

    private void irARutas() {

        cambiarColorPanel(jPanelRutas, colorMouseClicked);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorRutas = false;
        cambiarColorDepartamento = true;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorDeudas = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorDashboard = true;

        this.principal.irARutas();
    }

    private void irAEps() {
        cambiarColorPanel(jPanelEps, colorMouseClicked);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorEps = false;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorDepartamento = true;
        cambiarColorDeudas = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;
        
        this.principal.irAEps();
    }

    private void cambiarColorPanel(JPanel jPanel, Color color) {
        jPanel.setBackground(color);
    }

    private void irADeudas() {
        cambiarColorPanel(jPanelDeudas, colorMouseClicked);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseExited);
        cambiarColorDeudas = false;
        cambiarColorDepartamento = true;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = true;
        this.principal.irAPanelDeudas();
    }

    private void irADirectivoInicio() {
        cambiarColorPanel(jPanelDeudas, colorMouseExited);
        cambiarColorPanel(jPanelPersonas, colorMouseExited);
        cambiarColorPanel(jPanelAreas, colorMouseExited);
        cambiarColorPanel(jPanelCursos, colorMouseExited);
        cambiarColorPanel(jPanelDepartamentos, colorMouseExited);
        cambiarColorPanel(jPanelEps, colorMouseExited);
        cambiarColorPanel(jPanelRutas, colorMouseExited);
        cambiarColorPanel(jPanelDashboard, colorMouseClicked);
        cambiarColorDeudas = true;
        cambiarColorDepartamento = true;
        cambiarColorAreas = true;
        cambiarColorCursos = true;
        cambiarColorEps = true;
        cambiarColorPersonas = true;
        cambiarColorRutas = true;
        cambiarColorDashboard = false;
        
        this.principal.irADirectivos(usuario);
    }

}
